version: "3.9"

services:
  redis:
    image: "redis:7.0.2"
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: "redis-server --save 60 1 --loglevel warning"
    networks:
      - poker_network

  bot:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8000:8000"
    environment:
      - POKERBOT_TOKEN=${POKERBOT_TOKEN}
      - POKERBOT_REDIS_HOST=redis
      - POKERBOT_WEBHOOK_LISTEN=${POKERBOT_WEBHOOK_LISTEN}
      - POKERBOT_WEBHOOK_PORT=${POKERBOT_WEBHOOK_PORT}
      - POKERBOT_WEBHOOK_PATH=${POKERBOT_WEBHOOK_PATH}
      - POKERBOT_WEBHOOK_PUBLIC_URL=${POKERBOT_WEBHOOK_PUBLIC_URL}
      - POKERBOT_WEBHOOK_SECRET=${POKERBOT_WEBHOOK_SECRET}
      - POKERBOT_RATE_LIMIT_PER_MINUTE=${POKERBOT_RATE_LIMIT_PER_MINUTE}
      - POKERBOT_DEBUG_TRACE_MESSAGES=1
      - POKERBOT_METRICS_PORT=8000
      - POKERBOT_DB_POOL_MIN_SIZE=${POKERBOT_DB_POOL_MIN_SIZE:-10}
      - POKERBOT_DB_POOL_MAX_SIZE=${POKERBOT_DB_POOL_MAX_SIZE:-20}
      - POKERBOT_CACHE_L1_SIZE=${POKERBOT_CACHE_L1_SIZE:-1000}
      - POKERBOT_CACHE_L2_SIZE=${POKERBOT_CACHE_L2_SIZE:-5000}
      - POKERBOT_BATCH_ENABLED=${POKERBOT_BATCH_ENABLED:-true}
      - POKERBOT_BATCH_SIZE=${POKERBOT_BATCH_SIZE:-50}
    depends_on:
      - redis
    networks:
      - poker_network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - poker_network

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - poker_network

networks:
  poker_network:
    driver: bridge

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
