version: "3.9"

services:
  redis:
    image: "redis:7.0.2"
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: "redis-server --save 60 1 --loglevel warning"

  bot:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    # TLS در Nginx خاتمه می‌یابد و درخواست‌ها به 127.0.0.1:3000 هدایت می‌شود،
    # بنابراین کانتینر فقط روی لوپ‌بک گوش می‌دهد.
    environment:
      - POKERBOT_TOKEN=$POKERBOT_TOKEN
      - POKERBOT_REDIS_HOST=redis
      - POKERBOT_WEBHOOK_LISTEN=$POKERBOT_WEBHOOK_LISTEN
      - POKERBOT_WEBHOOK_PORT=$POKERBOT_WEBHOOK_PORT
      - POKERBOT_WEBHOOK_PATH=$POKERBOT_WEBHOOK_PATH
      - POKERBOT_WEBHOOK_PUBLIC_URL=$POKERBOT_WEBHOOK_PUBLIC_URL
      - POKERBOT_WEBHOOK_SECRET=$POKERBOT_WEBHOOK_SECRET
      - POKERBOT_RATE_LIMIT_PER_MINUTE=$POKERBOT_RATE_LIMIT_PER_MINUTE
      - POKERBOT_DEBUG_TRACE_MESSAGES=1
      - POKERBOT_DB_POOL_MIN_SIZE=$POKERBOT_DB_POOL_MIN_SIZE
      - POKERBOT_DB_POOL_MAX_SIZE=$POKERBOT_DB_POOL_MAX_SIZE
      - POKERBOT_DB_COMMAND_TIMEOUT=$POKERBOT_DB_COMMAND_TIMEOUT
      - POKERBOT_CACHE_L1_SIZE=$POKERBOT_CACHE_L1_SIZE
      - POKERBOT_CACHE_L1_TTL=$POKERBOT_CACHE_L1_TTL
      - POKERBOT_CACHE_L2_TTL=$POKERBOT_CACHE_L2_TTL
      - POKERBOT_CACHE_DEFAULT_TTL=$POKERBOT_CACHE_DEFAULT_TTL

volumes:
  redis_data:
