global:
  resolve_timeout: 5m

route:
  receiver: 'poker-admin'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 30m

receivers:
  - name: 'poker-admin'
    webhook_configs:
      - url: 'http://alert-bridge:9099/webhook/alertmanager'
        send_resolved: true
        max_alerts: 0

inhibit_rules: []
